site_name: KaaS
site_description: Knowledge as a Service.
site_author: Jimmy Briggs
site_url: https://jimbrig.github.io/KaaS-New/
copyright: Copyright &copy; 2022 Jimmy Briggs
repo_url: https://jimbrig/KaaS-New/
repo_name: jimbrig/KaaS-New
remote_branch: gh-pages
edit_uri: blob/main/
use_directory_urls: true
docs_dir: .docs

theme:
  name: 'material'
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  - toc:
      permalink: true

plugins:
  - search
  - roamlinks
