on: [push]

name: Convert Links

jobs:
  install:
    name: Install obsidian-export
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
      - run: cargo install obsidian-export