name: Convert-Links
on:
  push:
    branches: [ develop ] # note: develop branch is the branch obsidian pushes to
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Rename _READMEs
        run: find . -name '*_README.md' -execdir mv -i {} README.md ";"
      - name: setup rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: install obsidian-export
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: obsidian-export
      - name: obsidian-export
        run: mkdir tmp && obsidian-export . tmp --frontmatter never && cp tmp/* . -f -r && rm -r tmp
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_email: jimmy.briggs@jimbrig.com
          author_name: 'Jimmy Briggs'
          message: 'chore: convert mdlinks via obsidian-export and rename READMEs'
          branch: main
          force: true
