name: Publish Vault
on:
  push:
    branches: [ develop ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-roamlinks-plugin
      - run: mkdir .docs && cp * .docs -r -f
      - run: mkdocs gh-deploy --force
